### ISSUE TITLE
render a string

### ISSUE THREAD

**Issue by prepare** [vidstige/NRasterizer#17]
Do you want to use cached glyph?
This should be used, it is  about performance.

![cahced_glyph](https://cloud.githubusercontent.com/assets/7447159/19414957/5f089d3c-9389-11e6-8c81-b3cbffe242de.png)

---

This, 
from my latest, render a string ,
with Tahoma 11 pts

![tahoma_11pts](https://cloud.githubusercontent.com/assets/7447159/19414753/bec50254-9381-11e6-8ebb-07b23d84eb90.png)

---

Enable kerning option
![kern1](https://cloud.githubusercontent.com/assets/7447159/19415069/d938e216-938d-11e6-82f1-6617e9c5e866.png)

**Comment by vidstige** [comment]
Would be great improvement, but right now I think we should focus on removing the duplicated code. I think best would be if your repo could use a NuGet package instead. Once we have that we can start with performance optimizations.
