### ISSUE TITLE
fixed cmap glyphIdArrayLength

### ISSUE THREAD

**Issue by prepare** [vidstige/NRasterizer#20]
I found a bug in cmap's calculation of  glyphIdArrayLength 
I test with tahoma font, on Windows

 with character unicode3652 => ไ

"IndexOutOfRange exception"

![cmap_err](https://cloud.githubusercontent.com/assets/7447159/19417583/bc1eafce-93da-11e6-8900-57263b58a31c.png)

I reviewed what size of the glyphIdArray should be,
according to //https://www.microsoft.com/typography/otspec/cmap.htm

> This obscure indexing trick works because glyphIdArray immediately follows idRangeOffset in the font file.
> The C expression that yields the glyph index is:
> 
> ```
> *(idRangeOffset[i]/2 
> + (c - startCount[i]) 
> + &idRangeOffset[i])
> ```

---

so, I fixed it as describe in picture below.

![cmap_glyphidarray](https://cloud.githubusercontent.com/assets/7447159/19417600/35618f32-93db-11e6-9bcd-a37830f2e5d3.png)

---

I also send you a pull request,
but you can just copy-n-paste.

**Comment by vidstige** [comment]
Fixed in #21. Thank you!
