### ISSUE TITLE
someone may want the nuget package

### ISSUE THREAD

**Issue by prepare** [vidstige/NRasterizer#32]
Hello @vidstige,

You may have your nuget packet customer here :)
please consider this.

NOpenType-based code is used in this Repo.
It may be better with nuget packet of NOpenType.

your NOpenType-based code  has been integrated in this
https://github.com/JimBobSquarePants/ImageSharp/issues/38

and they talk about nuget here
https://github.com/JimBobSquarePants/ImageSharp/pull/45

**Comment by vidstige** [comment]
@prepare thanks for the ping!

@JimBobSquarePants I'll look into publishing the NuGet shortly.

**Comment by tocsoft** [comment]
For ImageSharp it would be great to have a package targeting `netstandard1.1` or lower (think you have to have 1.1 for streams to work but i could be making that up.) then we can then pull it in as a NuGet dependency directly instead of taking a source only copy.

**Comment by vidstige** [comment]
Alright, I pushed a package. It might not be indexed yet, but please try it out [here](https://www.nuget.org/packages/NOpenType/0.1.2).
